### ISSUE TITLE
[Store] Broken layout

### ISSUE THREAD

**Issue by HuanDoan** [zzs-training/html-book-store#30]
Page store is broken on branch `develop`

<img width="1661" alt="image" src="https://user-images.githubusercontent.com/20861694/216799818-74da6ca6-65fe-4d7a-822a-4da80754cace.png">

**Comment by DatQTruongCr** [comment]
I fixed all bug at branch "issue-fixbrokendevelop" and waiting your confirm. Thank you your time.

**Comment by DatQTruongCr** [comment]
Resolve #30
