### ISSUE TITLE
[Contact] Broken

### ISSUE THREAD

**Issue by HuanDoan** [zzs-training/html-book-store#31]
Page contact is broken on branch `develop`

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/20861694/216799875-bce8372c-6517-4c32-b633-f99cfbdc7133.png">

**Comment by DatQTruongCr** [comment]
I fixed all bug at branch "issue-fixbrokendevelop" and waiting your confirm. Thank you your time.

**Comment by DatQTruongCr** [comment]
Resolve #31
