### ISSUE TITLE
[Product detail] Broken

### ISSUE THREAD

**Issue by HuanDoan** [zzs-training/html-book-store#32]
Page `product detail` is broken on branch `develop`

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/20861694/216799937-ff317b85-4b64-4710-b15e-d971432822a6.png">

**Comment by DatQTruongCr** [comment]
I fixed all bug at branch "issue-fixbrokendevelop" and waiting your confirm. Thank you your time.

**Comment by DatQTruongCr** [comment]
Resolve #32
